// Free consumer email domains. Sending to these is blocked unless the
// campaign setting allow_free_domains is explicitly true (§14).
export const freeDomains = new Set([
  "gmail.com",
  "googlemail.com",
  "yahoo.com",
  "yahoo.co.uk",
  "hotmail.com",
  "hotmail.co.uk",
  "outlook.com",
  "live.com",
  "live.co.uk",
  "msn.com",
  "aol.com",
  "icloud.com",
  "me.com",
  "mac.com",
  "protonmail.com",
  "proton.me",
  "gmx.com",
  "gmx.de",
  "mail.com",
  "zoho.com",
  "yandex.com",
  "yandex.ru",
]);

// Common disposable-email domains for layer-0 verification. Not exhaustive —
// providers in the verify chain catch the tail.
export const disposableDomains = new Set([
  "mailinator.com",
  "guerrillamail.com",
  "10minutemail.com",
  "temp-mail.org",
  "tempmail.com",
  "throwawaymail.com",
  "yopmail.com",
  "getnada.com",
  "trashmail.com",
  "sharklasers.com",
  "dispostable.com",
  "maildrop.cc",
  "fakeinbox.com",
  "mintemail.com",
  "mytemp.email",
  "tempinbox.com",
  "spamgourmet.com",
  "mailnesia.com",
  "mail-temp.com",
  "burnermail.io",
]);

// Role accounts — flagged risky at layer 0.
export const roleAccounts = new Set([
  "admin",
  "info",
  "support",
  "sales",
  "contact",
  "hello",
  "help",
  "office",
  "team",
  "billing",
  "accounts",
  "hr",
  "jobs",
  "careers",
  "marketing",
  "no-reply",
  "noreply",
  "postmaster",
  "webmaster",
  "abuse",
]);
