// Spam-trigger lint list. Matched case-insensitively as whole phrases.
// Keep in config, never inline (build brief §16).
export const spamWords: string[] = [
  "100% free",
  "act now",
  "amazing deal",
  "apply now",
  "be your own boss",
  "buy now",
  "cash bonus",
  "cheap",
  "click here",
  "click below",
  "congratulations",
  "credit card",
  "double your",
  "earn extra cash",
  "exclusive deal",
  "fast cash",
  "free access",
  "free consultation",
  "free gift",
  "free money",
  "free trial",
  "get paid",
  "guarantee",
  "guaranteed",
  "increase sales",
  "instant",
  "limited time",
  "make money",
  "million dollars",
  "miracle",
  "no catch",
  "no cost",
  "no obligation",
  "no risk",
  "once in a lifetime",
  "order now",
  "prize",
  "promise you",
  "pure profit",
  "risk-free",
  "satisfaction guaranteed",
  "save big",
  "special promotion",
  "this won't last",
  "urgent",
  "winner",
  "work from home",
];

// Flattery clichés and AI-tell phrases banned from generated copy.
export const bannedPhrases: string[] = [
  "i hope this email finds you well",
  "i came across your profile",
  "i was impressed by",
  "i couldn't help but notice",
  "as an ai",
  "in today's fast-paced world",
  "cutting-edge",
  "synergy",
  "revolutionize",
  "game-changer",
  "unlock the power",
  "take your business to the next level",
  "quick question",
  "just circling back",
  "just checking in",
  "touching base",
];
